# Generated by Django 5.1.4 on 2024-12-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=100)),
                ('category', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
