# Generated by Django 5.1.4 on 2025-01-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0005_ewasterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ewasterequest',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='ewasterequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
