# Generated by Django 5.1.4 on 2025-01-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0006_remove_ewasterequest_submitted_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
