# Generated by Django 5.1.4 on 2025-01-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0008_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
