# Generated by Django 5.1.4 on 2025-01-04 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewasterequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ewaste_app.user'),
        ),
    ]
