# Generated by Django 5.1.4 on 2025-01-04 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0013_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ewaste_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ewaste_app.user')),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
