# Generated by Django 5.1.4 on 2025-01-18 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0017_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
