# Generated by Django 5.1.4 on 2025-02-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ewaste_app', '0024_otpverification2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification2',
        ),
    ]
